### ISSUE TITLE
stream RGB data

### ISSUE THREAD

**Issue by Changliu52** [bmegli/network-hardware-video-encoder#10]
Hi @bmegli 
Just wondering if you could share a script to stream rgb images?
I have the pixel format set to `hw_config_.pixel_format = "bgr0";`

and trying to stream with the following code
```
	static uint16_t framenumber_ = 0;
	struct nhve_frame frame = { 0 };
	frame.linesize[0] = color.step[0];

	frame.data[0] = (uint8_t*)color.ptr();
	frame.framenumber = framenumber_;
	
	if (nhve_send_frame(streamer_color_,&frame)) {
		NODELET_ERROR ("nhve_send_frame failed to send"); //break on error
		return 1;
	}

	framenumber_++;
```

and also tried
```
cv::Mat bgr[3];   //destination array
	cv::split(color,bgr);//split source  
	static uint16_t framenumber_ = 0;
	struct nhve_frame frame = { 0 };
	frame.linesize[0] = frame.linesize[1] = frame.linesize[2] = bgr[0].step[0];

	frame.data[0] = bgr[0].ptr();
	frame.data[1] = bgr[1].ptr();
	frame.data[2] = bgr[2].ptr();
	frame.framenumber = framenumber_;
	
	if (nhve_send_frame(streamer_color_,&frame)) {
		NODELET_ERROR ("nhve_send_frame failed to send"); //break on error
		return 1;
	}

	framenumber_++;
```
It compiles fine but always come up with this runtime error:
```
[AVHWFramesContext @ 0x55a324ca6ba0] Map surface 0x4000013.
Assertion abs(src_linesize) >= bytewidth failed at src/libavutil/imgutils.c:313
 05/05 00:32:40,334 ERROR [140507744708352] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs)
```
please advice the possible solution.

Thank you in advance.

Chang

**Comment by bmegli** [comment]
Hi @Changliu52,

The reference here is:
- [HVE documentation](https://bmegli.github.io/hardware-video-encoder/structhve__config.html)
- which points to [FFmpeg pixel formats](https://ffmpeg.org/doxygen/3.4/pixfmt_8h.html#a9a8e335cf3be472042bc9f0cf80cd4c5)

precisely:

AV_PIX_FMT_BGR0 | packed BGR 8:8:8, 32bpp, BGRXBGRX... X=unused/undefined
-- | --

There are two problems with your implementation:
- bgr0 is not a planar format (this means it is encoded in a single plane, not multiple planes)
- bgr0 is 32 bit per pixel, 8 bit per channel with alpha value ignored (this is *0* in bgr*0*)

So you should have:
- single array of bgr0 data
- which could be for example uint32 array of width x height size
- if stride matches witdth * 4 (or width * sizeof(uint32_t))

For example

```
//in real world this would be dynamically allocated
uint32_t bgr0_data[WIDTH*HEIGHT];
...

//only single plane is used, this is not a planar format
frame.data[0] = bgr0_data;
//here we have no padding, so linesize is simply width * size of single element
frame.linesize[0] = WIDTH * sizeof(uint32_t);
...

```

**Comment by bmegli** [comment]
```
[AVHWFramesContext @ 0x55a324ca6ba0] Map surface 0x4000013.
Assertion abs(src_linesize) >= bytewidth failed at src/libavutil/imgutils.c:313
```

And the error message is because:
- the encoder expects at least 4 * width bytes per line
- and you supply 1 * width bytes per line in one case (`frame.data[0] = bgr[0].ptr())`
- and probably 3 * width bytes per line in the second case

**Comment by Changliu52** [comment]
Great. Works perfectly now!! Thank you so much.
