### ISSUE TITLE
Bandwidth utilisation not adjustable

### ISSUE THREAD

**Issue by Changliu52** [bmegli/network-hardware-video-encoder#15]
Hi @bmegli 

I was testing the performance of the encoding with different bandwidth parameters

the initilisation I used was:
```
hw_config_.pixel_format = "nv12";
hw_config_.profile = FF_PROFILE_H264_CONSTRAINED_BASELINE;
hw_config_.encoder = NULL;
hw_config_.width = 1280;
hw_config_.height= 720;
hw_config_.framerate = 30;
hw_config_.max_b_frames = 0;
hw_config_.device = NULL; //NULL as last argv argument, or device path
hw_config_.bit_rate = 4000000;
```

However, the traffic monitoring in linux only showing 1.8-2 mbps. I have checked different bit_rate parameters (10,000,000 and 20,000,000) but not really made any difference. Did I reached some limitations of the hardware? (not sure if the h264 is able to handle 1280x720 resolution.

Also I did have two NHVE initialised with different bit rate and different port. would that make a difference?

Best Regards,
Chang

**Comment by bmegli** [comment]
I think I have seen such problem before with a combination of driver, libva and ffmpeg version, for example [here](https://github.com/bmegli/hardware-video-encoder/issues/21)

> 19.04
> I used it on m3-8100Y with GPD Win2, worked out of the box with:
> Ubuntu MATE 19.04 for GPD Pocket 2 & GPD WIN 2
> H264 and HEVC Main10 worked however I had doubts whether bitrate control worked correctly. Didn't seem so.

When live streaming complex material it should be easy to spot, the quality is simply bad.

What platform are you on (generation), which driver do you use, what OS/FFmpeg version?

I would start debugging it by:
- enabling verbose/debug FFmpeg logging options in [HVE](https://github.com/bmegli/hardware-video-encoder/blob/master/hve.c#L68)
- looking what information about VAAPI rate control is emmitted
- try to switch driver if it is possible (i965 vs iHD) for your generation
- try to switch to CBR instead of VBR (the default) using command line FFmpeg and see if it helps like [here](https://trac.ffmpeg.org/wiki/Hardware/VAAPI) in "Mapping options from libx264" (I am not sure it is entirely up to date with new FFMpeg versions)

> Also I did have two NHVE initialised with different bit rate and different port. would that make a difference?

Should not in theory but (as side note) I would check gpu usage with:

```bash
sudo intel_gpu_top
```

H.264 should not require much really but HEVC depending on platform generation can be heavy on GPU, see for example [this](https://github.com/bmegli/realsense-network-hardware-video-encoder/issues/12#issuecomment-621338360) where double HEVC stream uses 65% of SBCs gpu and barely keeps up to 30 FPS. Just in case, you may control speed/quality trade-off with `compression_level`.

**Comment by bmegli** [comment]
Also if your material is not complex (e.g. static scene) from what I remember you may get low bitrate with VBR.

Make sure you have complex scene (e.g. moving camera) that actually requires some bitrate.

**Comment by Changliu52** [comment]
Thanks @bmegli 
I'm running ubuntu 18.04 on UPS-EDGE-X70864-U01.
Will test the suggestions and report back.

Best Regards

**Comment by Changliu52** [comment]
Intel ATOM Quad-Core up to 2.0GHz x7-E3950
Graphic: Intel HD Graphic 500

**Comment by bmegli** [comment]
Looking at ark it is [ApolloLake](https://ark.intel.com/content/www/pl/pl/ark/products/96488/intel-atom-x7-e3950-processor-2m-cache-up-to-2-00-ghz.html)

By cross-checking with [FFmpeg QuickSync](https://trac.ffmpeg.org/wiki/Hardware/QuickSync) it has gen 9 graphics.
Apollo Lake | gen9 | VP9, H.265 Main10 decode.
-- | -- | --

By looking at table `Intel open source media stack` in link above we see:



Project Name | Supported Gen Graphics | Open Source Repo
-- | -- | --
MSDK | gen8+ | ​https://github.com/Intel-Media-SDK/MediaSDK
Libva | gen5+ | ​https://github.com/intel/libva
i965 driver | gen5 ~ gen9.5 | ​https://github.com/intel/intel-vaapi-driver
iHD driver | gen8+ | ​https://github.com/intel/media-driver

that it should probably work with both i965 and iHD.

Crosschecking with [iHD support matrix](https://github.com/intel/media-driver#decodingencoding-features) we see that even with iHD only it has two different ways to encode H.264

E - Hardware Encoding, Low Power Encoding(VDEnc/Huc)
Es - Hardware(PAK) + Shader(media kernel+VME) Encoding

Es only with full featured build.

To get full feature build in Ubuntu

```
# this is for iHD full feature build
sudo apt install intel-media-va-driver-non-free
```

Ideally also before and after updating to see if it changes anything:

```bash
LIBVA_DRIVER_NAME=iHD vainfo --display drm --device /dev/dri/renderD128
```

**Comment by bmegli** [comment]
Quoting myself:

> To get full feature build in Ubuntu

```bash
# this is for iHD full feature build
sudo apt install intel-media-va-driver-non-free
```

> Ideally also before and after updating to see if it changes anything:

```bash
LIBVA_DRIVER_NAME=iHD vainfo --display drm --device /dev/dri/renderD128
```

Sorry - the above was for Ubuntu 20.04 (which has both i965 and iHD drivers), not 18.04 (which has i965 driver)

**Comment by bmegli** [comment]
@Changliu52 

You can also:

1. Check with vainfo if your hardware supports alternative encoding paths:

```bash
vainfo --display drm --device /dev/dri/renderD128
#VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
# alternative Low Power fixed function encoding
#VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
```

2. Check issues (and solutions) for the [vaapi driver](https://github.com/intel/intel-vaapi-driver/issues)

(search for bitrate, rate control, etc, both in open and closed)

3. Try Ubuntu 20.04 which has newer FFmpeg and both i965 and iHD drivers

Some of the issues with 20.04 are already fixed

**Comment by Changliu52** [comment]
Thank you so much for the suggestions @bmegli 
I have tried `sudo apt install intel-media-va-driver-non-free` and did some search around.
actually ubuntu 18.04 doesn't yet support that.

I did some further test and realised that the intel-gpu-top gives about 10% utilisation, and i think because of some other part of the code, the CPU is pretty busy like 80% in all cores. and checked my raw depth images is about 15 FPS instead of 30 FPS as I set. 

Not sure why this happened, but when I set the framerate to 15 in for NHVE, the bitrate control seems working. 
I can now set the bitrate and the network monitor responds, although numbers is normally about half of the bitrate I set. I guess the bitrate setting is the maximum number while the network monitor shows the averaged activities in the network.

**Comment by bmegli** [comment]
@Changliu52 

The default rate control is VBR
 
If you want CBR replace HVE [line](https://github.com/bmegli/hardware-video-encoder/blob/59f416f0f1efbc1d2222f0f125309a461f793ac2/hve.c#L101)

with:

```C
h->avctx->bit_rate = h->avctx->rc_max_rate = config->bit_rate;
```

This will probably keep you closer to target bitrate.
