### ISSUE TITLE
error compiling in ubuntu 16.04

### ISSUE THREAD

**Issue by Changliu52** [bmegli/network-hardware-video-encoder#3]
Great package!

I have installed the ffmpeg-3.4.1 from source
and installed all the rest dependencies via apt install.

However, I still get the following error:
```
[  7%] Building C object minimal-latency-streaming-protocol/CMakeFiles/mlsp.dir/mlsp.c.o
[ 14%] Linking C static library libmlsp.a
[ 14%] Built target mlsp
[ 21%] Building C object hardware-video-encoder/CMakeFiles/hve.dir/hve.c.o
[ 28%] Linking C shared library libhve.so
[ 28%] Built target hve
[ 35%] Building C object CMakeFiles/nhve.dir/nhve.c.o
[ 42%] Linking C static library libnhve.a
[ 42%] Built target nhve
[ 50%] Building C object CMakeFiles/nhve-stream-h264.dir/examples/nhve_stream_h264.c.o
[ 57%] Linking C executable nhve-stream-h264
hardware-video-encoder/libhve.so: undefined reference to `av_hwframe_get_buffer'
hardware-video-encoder/libhve.so: undefined reference to `av_hwframe_ctx_init'
hardware-video-encoder/libhve.so: undefined reference to `av_hwframe_ctx_alloc'
hardware-video-encoder/libhve.so: undefined reference to `av_hwframe_transfer_data'
hardware-video-encoder/libhve.so: undefined reference to `avcodec_send_frame'
hardware-video-encoder/libhve.so: undefined reference to `av_hwdevice_ctx_create'
hardware-video-encoder/libhve.so: undefined reference to `avcodec_receive_packet'
collect2: error: ld returned 1 exit status
CMakeFiles/nhve-stream-h264.dir/build.make:97: recipe for target 'nhve-stream-h264' failed
make[2]: *** [nhve-stream-h264] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/nhve-stream-h264.dir/all' failed
make[1]: *** [CMakeFiles/nhve-stream-h264.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Please help.

Best Regards,
Chang

**Comment by bmegli** [comment]
Hi @Changliu52,

Looks like you are:
- compiling with the correct headers
- but not linking against the correct shared library version 

I would: 
- make sure that the library links against correct libavcodec/avutil
- try `sudo ldconfig` (this refreshes links to shared libraries)

------------------------------------------------------

Alternatively - I have just checked with 16.04.6 LTS live cd.

The libraries build and run with FFmpeg from this [ppa](https://tecadmin.net/install-ffmpeg-on-linux/).

```bash
sudo add-apt-repository ppa:jonathonf/ffmpeg-4
sudo apt-get update
sudo apt-get install ffmpeg libavcodec-dev libavutil-dev
```

Kind regards

**Comment by bmegli** [comment]
Also, if compiling FFmpeg from source you should add `--enable-vaapi ` flag when running `./configure`.

This is necessary for hardware encoding/decoding support through VAAPI.

**Comment by Changliu52** [comment]
Brilliant!
```
sudo add-apt-repository ppa:jonathonf/ffmpeg-4
sudo apt-get update
sudo apt-get install ffmpeg libavcodec-dev libavutil-dev
```
works like a charm!

**Comment by bmegli** [comment]
Turns out this didn't solve the problem really.

Only the simplest scenario with NV12 pixel format works in NHVE in 16.4 ecosystem (GPU driver, libva, VA-API),

I would say that solving those problems is not worth anybody's time. Its time to switch to 18.04 LTS or 20.04 LTS next month.
