### ISSUE TITLE
Stream opencv images cv::mat

### ISSUE THREAD

**Issue by Changliu52** [bmegli/network-hardware-video-encoder#5]
Hi @bmegli 
I'm trying to stream standard opencv cv::mat data through h264.

hw_config:
```
hw_config_.pixel_format = "nv12";
hw_config_.profile = FF_PROFILE_H264_CONSTRAINED_BASELINE; 
hw_config_.encoder = "h264_vaapi";
hw_config_.width = 640;
hw_config_.height= 480;
hw_config_.framerate = 30;
hw_config_.device = "/dev/dri/renderD128"
```

When streaming, i use the following
```
nhve_frame frame = {0};

frame.linesize[0] =  hw_config_.width;
frame.data[0] = y.ptr(); // y is CV_8UC1, 640x480

frame.linesize[1] =  hw_config_.width;//hw_config_.width;
frame.data[1] = uv.ptr();// uv is CV_8UC1, 640x240

frame.framenumber = framenumber_;
nhve_send_frame(streamer_, &frame);
```

It comes out as the following error:
```
corrupted size vs. prev_size
```
Are you able to spot anything wrong?

Thank you in advance.
Chang

**Comment by bmegli** [comment]
Hi @Changliu52,

You are missing the details how you create your opencv Mat objects.

Note that opencv uses convention:
- `Mat (int rows, int cols, int type)`
- which is `MAT(height, width)`, not `Mat(width, height)`

Also, in theory, you should use `Mat.step[0]` for the linesize, in case stride doesn't match width.

I have added minimalistic OpenCV (see [diff](https://github.com/bmegli/hardware-video-encoder/commit/c833149635db629c32564007c760862b6c3cbb30)) example in HVE  in `opencv` branch temporarily.

You may test it with:
```bash
# build
git clone https://github.com/bmegli/hardware-video-encoder.git
cd hardware-video-encoder
git checkout opencv
mkdir build
cd build
cmake ..
make

# run
./hve-encode-raw-h264 10 /dev/dri/renderD128
ffplay output.h264
```

The interesting fragment of code:

```bash
int encoding_loop(struct hve *hardware_encoder, FILE *output_file)
{
	struct hve_frame frame = { 0 };
	int frames=SECONDS*FRAMERATE, f, failed;

	//we are working with NV12 because we specified nv12 pixel format
	//when calling hve_init, in principle we could use other format
	//if hardware supported it (e.g. RGB0 is supported on my Intel)

	Mat luminance(HEIGHT, WIDTH,CV_8UC1, Scalar(128));
	Mat uv(HEIGHT/2,WIDTH,CV_8UC1, Scalar(128));

	//fill with your stride (width including padding if any)
	frame.linesize[0] = frame.linesize[1] = luminance.step[0];

	//encoded data is returned in FFmpeg packet
	AVPacket *packet;

	for(f=0;f<frames;++f)
	{
		//prepare dummy image data, normally you would take it from camera or other source
		//memset(Y, f % 255, WIDTH*HEIGHT); //NV12 luminance (ride through greyscale)
		//memset(color, 128, WIDTH*HEIGHT/2); //NV12 UV (no color really)

		//fill hve_frame with pointers to your data in NV12 pixel format
		frame.data[0]=luminance.ptr();
		frame.data[1]=uv.ptr();

		//encode this frame
		if( hve_send_frame(hardware_encoder, &frame) != HVE_OK)
			break; //break on error

		while( (packet=hve_receive_packet(hardware_encoder, &failed)) )
		{
			//packet.data is H.264 encoded frame of packet.size length
			//here we are dumping it to raw H.264 file as example
			//yes, we ignore the return value of fwrite for simplicty
			//it could also fail in harsh real world...
			fwrite(packet->data, packet->size, 1, output_file);
		}

		//NULL packet and non-zero failed indicates failure during encoding
		if(failed)
			break; //break on error
	}

	//flush the encoder by sending NULL frame, encode some last frames returned from hardware
	hve_send_frame(hardware_encoder, NULL);
	while( (packet=hve_receive_packet(hardware_encoder, &failed)) )
		fwrite(packet->data, packet->size, 1, output_file);

	//did we encode everything we wanted?
	//convention 0 on success, negative on failure
	return f == frames ? 0 : -1;
}

```

Edits:
- `/hve-encode-raw-h264` instead of hevc

**Comment by Changliu52** [comment]
That works perfectly! Thank you so much for your guidance!

**Comment by bmegli** [comment]
@Changliu52,

Some optimization related afterthoughts:

1. You don't have to use NV12 pixel format, VAAPI supports uploading in other formats.

My hardware (KabyLake)/OS reports (those are not guaranteed to work in all scenarios):
- nv12
- yuv420p
- yuyv422
- uyvy422
- yuv422p
- rgb0
- bgr0
- p010le

For more information see [HVE docs](https://bmegli.github.io/hardware-video-encoder/structhve__config.html).

2.  `FF_PROFILE_H264_CONSTRAINED_BASELINE` gives access to limited H.264 features and may mean increased bandwidth requirements (less advanced encoding but supported more broadly)

3. B frames

hw_config->max_b_frames

I typically use no B frames. This minimizes latency but at the cost of quality/size. You may want to increase that. Typical value here is 2.

Note that the output of encoder will be delayed by max_b_frames+1 relative to the input. This means that you have to push multiple frames before you will start to receive any encoded data. At 30 fps single frame of delay is additional ~ 33 ms.
