### ISSUE TITLE
Force keyframe in streaming

### ISSUE THREAD

**Issue by Changliu52** [bmegli/network-hardware-video-encoder#6]
Hi @bmegli 
Thank you for helping out.
We were testing h264 streaming. It generally performs quite well in a good network.
But what we found in an unreliable network, is that the quality of the video does not recover and also the receiver has to start before the streamer to get the keyframe.

I wonder if there is any way we can force the streamer to send keyframe periodically in order to recover even when dropping packets or restarting the receiver?

Thanks.
Chang

**Comment by bmegli** [comment]
Hi @Changliu52,

> I wonder if there is any way we can force the streamer to send keyframe periodically

It already does (sends keyframes periodically). Whether you could configure the period is another question and needs some investigation.

> the receiver has to start before the streamer to get the keyframe.

It doesn't. Keyframes are emitted periodically. If the receiver starts later it will pick up the stream at the first keyframe it sees. Unless you are using outdated version of UNHVD (or rather NHVD) which at some point in the past had this problem.

---------------------------------------------------

The root cause of the problem is probably dropped packets.

You could:
- simplify network architecture (in my case point-to-point streaming helps, without wireless AP in between, see this [issue](https://github.com/bmegli/unity-network-hardware-video-decoder/issues/10))
- replace MLSP protocol with something more mature that handles retransmissions
- replace MLSP UDP transport with TCP/IP if you can live with TCP/IP problems
- extend MLSP to be more robust
- transmit wirelessly with more power if it is the problem (if your device supports higher powers you could change WiFi regulatory domain policy, e.g. Bolivia, but it may be illegal in your country)

It is very easy to setup point-to-point streaming in Ubuntu 18.04 and later (a few clicks to turn on hot-spot) so you could check if it makes the difference.

As far as MLSP is concerned it was designed for rapid experiments (simplicity). 
I have no plans at this moment to make it more complex.

**Comment by bmegli** [comment]
Come to think about that there is one more thing.

Looking at the [issues](https://github.com/bmegli/network-hardware-video-decoder/issues/1) of NHVD (UNHVD uses it as native plugin) I forgot to implement flushing hardware decoder in case of timeout.

This would end up [here](https://github.com/bmegli/network-hardware-video-decoder/blob/cd48f0a394384aa9c67d764a472179d924415580/nhvd.cpp#L115).

The symptoms might be similar, e.g. the video not recovering without serious movement in the area.

**Comment by bmegli** [comment]
> Looking at the issues of NHVD (UNHVD uses it as native plugin) I forgot to implement flushing hardware decoder in case of timeout.

I added flushing/draining the decoder in NHVD and UNHVD. I don't think this is the cause of the problem but this is the way it should be done anyway.

**Comment by bmegli** [comment]
Another thing that you could do:

Watch the `/proc/net/udp` for packet drops (last column). 

In case drops rise this means that packets reach your receiving PC but are dropped by the OS (e.g. the receiving application is doing something else and not handling them).

```bash
watch -d 'cat /proc/net/udp'
```

**Comment by bmegli** [comment]
For controlling keyframe period (for now) you may add the line in HVE [here](https://github.com/bmegli/hardware-video-encoder/blob/master/hve.c#L87)

More or less like this:

```C
h->avctx->gop_size = ...
```

Also have a look at [FFmpeg Codecs Documentation](https://www.ffmpeg.org/ffmpeg-codecs.html#VAAPI-encoders):
- `idr_interval` also looks interesting

**Comment by Changliu52** [comment]
Very cool. I will go ahead to implement them and report back. Thank you for the super useful suggestions!

**Comment by Changliu52** [comment]
Also want to check if this package also resent SPS&PPS packets also together with the keyframe? Our receiver is also looking for that one to initialise the stream.

Chang

**Comment by Changliu52** [comment]
> idr_interval also looks interesting

I was trying to set it through 
`h->avctx->priv_data->idr_interval = 3;`
doesn't seem to have that option.

**Comment by Changliu52** [comment]
found some code here https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/vaapi_encode.c#L1817

**Comment by bmegli** [comment]
> Also want to check if this package also resent SPS&PPS packets also together with the keyframe?

If you are using H.264 [this](https://github.com/bmegli/hardware-video-encoder/issues/23) should get you started

**Comment by bmegli** [comment]
> > idr_interval also looks interesting
> 
> I was trying to set it through
> `h->avctx->priv_data->idr_interval = 3;`
> doesn't seem to have that option.

This could actually make things worse.\
You would probably want every I frame to be IDR frame (idr_interval 0 or 1).

Warning - some guessing below.

Anyway, setting this probably has some effect only in open GOP mode.\
H.264 likely uses closed gop by default. I don't know about HEVC.

> found some code here https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/vaapi_encode.c#L1817

Possibly it is just easier to make sure you are in closed gop mode.

You could also draw some conclusion by analyzing bitstream NALs like in the post above.

**Comment by bmegli** [comment]
> I was trying to set it through
> `h->avctx->priv_data->idr_interval = 3;`
> doesn't seem to have that option.

You probably shouldn't mess with `priv_data`, think of it as private in C++.

The right way to set it would be through `avcodec_open2`[here](https://github.com/bmegli/hardware-video-encoder/blob/master/hve.c#L99) as additional option. This would also give you feedback whether option was set or not (function returns options that were not matched, see docs [here](https://ffmpeg.org/doxygen/3.4/group__lavc__core.html#ga11f785a188d7d9df71621001465b0f1d))

Something along the line:

```C
   AVDictionary *opts = NULL;   
   AVDictionaryEntry *t = NULL;
   av_dict_set_int(&opts, "idr_interval", 3, 0); 
   //some other options that are actually matched
   //av_dict_set_int(&opts, "low_power", 1, 0)
   //av_dict_set(&opts, "coder", "cavlc", 0);;

	if((err = avcodec_open2(h->avctx, codec, &opts)) < 0)
	{
		fprintf(stderr, "hve: cannot open video encoder codec\n");
		return hve_close_and_return_null(h);
	}

	AVDictionaryEntry *e;

	while (e = av_dict_get(opts, "", e, AV_DICT_IGNORE_SUFFIX)) {
		fprintf(stderr, "%s not set!\n", e->key);
	}

   //free opts somewhere
```

Anyway, examining the link you found with the implementation:
> found some code here https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/vaapi_encode.c#L1817

We may see that `idr_interval` was introduced in FFmpeg 4.2 so it probably wouldn't do anything unless you are on 4.2 or later.

Edit:
- updated link to point to correct place in new code
- the options dictionary is [copied in avcodec_open2](https://github.com/FFmpeg/FFmpeg/blob/release/3.4/libavcodec/utils.c#L662)
- original dictionary is [freed](https://github.com/FFmpeg/FFmpeg/blob/release/3.4/libavcodec/utils.c#L1131) in the same function
- a pointer to dictionary copy with unset options is returned to the user
- and it is now his responsibility to free this new dictionary, not the original one
- updated code snippet with simple note to free

Quite counter-intuitive, under-documented and error prone.

**Comment by bmegli** [comment]
Also if you want to know what is happening under the hood set log level to debug [here](https://github.com/bmegli/hardware-video-encoder/blob/master/hve.c#L51)

```C
av_log_set_level(AV_LOG_DEBUG);
```

**Comment by Changliu52** [comment]
Thank you so much for your suggestions!
I enabled `AV_LOG_DEBUG` and enabled `idr_interval` and `gop_size` using your example code.
The `gop_size` seems working because every 10 frame output one IDR stated in console (with and without `av_dict_set_int(&opts, "idr_interval", 3, 0);`:

```[AVHWFramesContext @ 0x557339596fe0] Map surface 0x4000013.
[AVHWFramesContext @ 0x557339596fe0] Unmap surface 0x4000013.
[h264_vaapi @ 0x5573395968a0] Encode frame: 640x480 (-9223372036854775808).
[h264_vaapi @ 0x5573395968a0] Pictures: IDR (50/50) P (51/51)
[h264_vaapi @ 0x5573395968a0] Issuing encode for pic 51/51 as type P.
[h264_vaapi @ 0x5573395968a0] Refers to: 50/50.
[h264_vaapi @ 0x5573395968a0] Input surface is 0x4000013.
[h264_vaapi @ 0x5573395968a0] Recon surface is 0x4000015.
[h264_vaapi @ 0x5573395968a0] Output buffer is 0x8000000.
[h264_vaapi @ 0x5573395968a0] Param buffer (23) is 0x8000005.
[h264_vaapi @ 0x5573395968a0] Packed header buffer (3) is 0x8000003/0x8000004 (59 bits).
[h264_vaapi @ 0x5573395968a0] Param buffer (24) is 0x8000002.
[h264_vaapi @ 0x5573395968a0] Sync to pic 51/51 (input surface 0x4000013).
[h264_vaapi @ 0x5573395968a0] Output buffer: 3124 bytes (status 00000000).
[h264_vaapi @ 0x5573395968a0] Output read for pic 51/51.
```

`idr_interval` seems not taking any effect.
also just for information, I was using the default ffmpeg in 18.04. the version output is:
```
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
```
Also wondering if there is a way to obtain the SPS/PPS directly from hve manually publish them periodically?

Chang

**Comment by bmegli** [comment]
> idr_interval seems not taking any effect.

> Anyway, examining the link you found with the implementation:
> > found some code here https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/vaapi_encode.c#L1817
> 
> We may see that `idr_interval` was introduced in FFmpeg 4.2 so it probably wouldn't do anything unless you are on 4.2 or later.
> 

Yes, [examinining your link with branch 3.4](https://github.com/FFmpeg/FFmpeg/blob/release/3.4/libavcodec/vaapi_encode.c) we see there was no such option at the time.

Also, I only said that it looked interesting, you probably don't have to touch it.

**Comment by bmegli** [comment]
> Also wondering if there is a way to obtain the SPS/PPS directly from hve manually publish them periodically?

Please, clarify what you mean.

> > Also want to check if this package also resent SPS&PPS packets also together with the keyframe?
> 
> If you are using H.264 [this](https://github.com/bmegli/hardware-video-encoder/issues/23) should get you started

Experiment:
- set gop_size to 10 in HVE `hve-encode-rawh264`, build
- run `./hve-encode-raw-h264 10 /dev/dri/renderD128`
- examine dumped raw H.264

```bash
h264_analyze output.h264 | grep "nal->nal_unit_type:"

0.5: nal->nal_unit_type: 7 #SPS
0.5: nal->nal_unit_type: 8 #PPS
0.5: nal->nal_unit_type: 5 #IDR
0.5: nal->nal_unit_type: 1 #non IDR
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 7 #SPS
0.5: nal->nal_unit_type: 8 #PPS
0.5: nal->nal_unit_type: 5 #IDR
0.5: nal->nal_unit_type: 1 #non IDR
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 7 
0.5: nal->nal_unit_type: 8 
0.5: nal->nal_unit_type: 5 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
0.5: nal->nal_unit_type: 1 
...
```

So, looks like they are published periodically.

**Comment by Changliu52** [comment]
That's really cool! I think that is what I want already!!
Thank you so much @bmegli
